#!/bin/sh

PNAME=snippets
SWD=`pwd`
VER=`sed -n 's/Version: \(.*\)/\1/p' DESCRIPTION`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -pR ../${PNAME} /tmp
rm -f /tmp/${PNAME}/mkdist

cd /tmp/${PNAME}

echo "Removing CVS and backup stuff ..."
find . -name CVS -o -name .svn | xargs rm -rf
find . -name \*~ | xargs rm -f
rm -rf .git*

echo "Creating package ..."
cd ..
R CMD build ${PNAME}
cd ${SWD}
cp /tmp/${PNAME}_${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz
